/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ros_android_example_hello_ros_MainActivity_RosThread */

#ifndef _Included_org_ros_android_example_hello_ros_MainActivity_RosThread
#define _Included_org_ros_android_example_hello_ros_MainActivity_RosThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ros_android_example_hello_ros_MainActivity_RosThread
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ros_android_example_hello_1ros_MainActivity_00024RosThread_run
  (JNIEnv *, jobject);

/*
 * Class:     org_ros_android_example_hello_ros_MainActivity_RosThread
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ros_android_example_hello_1ros_MainActivity_00024RosThread_stop
  (JNIEnv *, jobject);

/*
 * Class:     org_ros_android_example_hello_ros_MainActivity_RosThread
 * Method:    checkRosMaster
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ros_android_example_hello_1ros_MainActivity_00024RosThread_checkRosMaster
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_ros_android_example_hello_ros_MainActivity_RosThread
 * Method:    __RosThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ros_android_example_hello_1ros_MainActivity_00024RosThread__1_1RosThread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
